version: '3'
services:
  qrapi-flask:
    build: .
    ports:
      - 5001:5001
    volumes:
      - "./qrapi/:/app"
    restart: always
    environment:
      - FLASK_ENV=development
      - API_AUTHORIZATION_TOKEN=secret
