name: BuildDockerCore

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build core image
      run: docker build -t skalimat/qrapi -f dockercore/Dockerfile .

    - name: Push core image to dockerhub
      run: docker push skalimat/qrapi
